name: Tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test -coverprofile=unit.coverage.out ./day*
      - name: Upload coverage report
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: "unit.coverage.out"
          force-coverage-parser: "go"
